# Cloud Build configuration for deploying the ingestion service
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-ingestion-service:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-ingestion-service:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rag-ingestion-service'
      - '--image=gcr.io/$PROJECT_ID/rag-ingestion-service:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=540s'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--service-account=rag-ingestion-service@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'
      - '--no-allow-unauthenticated'  # Only allow authenticated requests

  # Create Cloud Scheduler job to trigger the service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'scheduler'
      - 'jobs'
      - 'create'
      - 'http'
      - 'rag-daily-ingestion'
      - '--schedule=0 2 * * *'  # Run at 2:00 AM every day
      - '--uri=https://rag-ingestion-service-HASH.a.run.app/ingest'  # Replace HASH with actual Cloud Run URL hash
      - '--http-method=POST'
      - '--oidc-service-account-email=rag-ingestion-service@$PROJECT_ID.iam.gserviceaccount.com'
      - '--message-body={"prefix": "documents/", "wait_for_completion": false}'
      - '--location=us-central1'
      - '--time-zone=America/Los_Angeles'
    # This step may fail if the job already exists, which is OK
    allowFailure: true

images:
  - 'gcr.io/$PROJECT_ID/rag-ingestion-service:$COMMIT_SHA'

substitutions:
  _REGION: us-central1