timeout: 1800s
# Cloud Build configuration for deploying the RAG ingestion service to Cloud Run
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rag-ingestion-service:$BUILD_ID', '.']
  
  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-ingestion-service:$BUILD_ID']
  
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/rag-ingestion-service:$BUILD_ID', 'gcr.io/$PROJECT_ID/rag-ingestion-service:latest']
  
  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-ingestion-service:latest']
  
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'rag-ingestion-service'
      - '--image=gcr.io/$PROJECT_ID/rag-ingestion-service:$BUILD_ID'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=540s'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--service-account=174522850388-compute@developer.gserviceaccount.com'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID'
      - '--no-allow-unauthenticated'
  
  # Display deployment success message
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "======================================================="
        echo "RAG Ingestion Service Deployed Successfully!"
        echo "======================================================="
        echo "See README.md for next steps to set up Cloud Scheduler."

# Images to keep in the registry
images:
  - 'gcr.io/$PROJECT_ID/rag-ingestion-service:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/rag-ingestion-service:latest'

# Default substitution values
substitutions:
  _REGION: us-central1

# Logging options
options:
  logging: CLOUD_LOGGING_ONLY